FROM base AS client

WORKDIR /app

# Копируем исходный код клиента
COPY client.cpp /app/client.cpp
COPY CMakeLists.txt /app/CMakeLists.txt
COPY generated /app/generated

# Собираем клиент
RUN mkdir -p build && cd build && cmake .. && make

# Запускаем клиент
CMD ["./build/client"]
