FROM base AS server

WORKDIR /app

# Копируем исходный код сервера
COPY server.cpp /app/server.cpp
COPY CMakeLists.txt /app/CMakeLists.txt
COPY generated /app/generated

# Собираем сервер
RUN mkdir -p build && cd build && cmake .. && make

# Запускаем сервер
CMD ["./build/server"]
